// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"strconv"

	models "github.com/Maxim-Ba/cv-backend/internal/models/gen"
	"github.com/Maxim-Ba/cv-backend/pkg/i18n"
)

type EntityFormData struct {
	EntityName string
	Fields     []FormField
	ActionURL  string
	Method     string // "POST" || "PUT"
	EntityID   int64
	CSRFToken  string
}

type FormField struct {
	Name        string
	Label       string
	Type        string
	Value       string
	ValueRU     string
	ValueEN     string
	Placeholder string
	Required    bool
	IsTextArea  bool
	Options     []FormFieldOption
}

type FormFieldOption struct {
	Value   string
	Label   string
	Checked bool
	Color   string
}

func ModalForm(data EntityFormData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"entityModal\" class=\"modal fade show\" style=\"display: block; background-color: rgba(0,0,0,0.5);\" tabindex=\"-1\" role=\"dialog\"><div class=\"modal-dialog modal-lg\" role=\"document\"><div class=\"modal-content\"><div class=\"modal-header\"><h5 class=\"modal-title\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if data.EntityID > 0 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "Редактировать ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(data.EntityName)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/view/components/components/modal.templ`, Line: 46, Col: 51}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "Добавить ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(data.EntityName)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/view/components/components/modal.templ`, Line: 48, Col: 41}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</h5><a href=\"?\" class=\"close\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></a></div><div class=\"modal-body\"><form method=\"POST\" action=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 templ.SafeURL
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinURLErrs(data.ActionURL)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/view/components/components/modal.templ`, Line: 56, Col: 48}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\"><input type=\"hidden\" name=\"_method\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(data.Method)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/view/components/components/modal.templ`, Line: 57, Col: 61}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "\"> <input type=\"hidden\" name=\"csrf_token\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var6 string
		templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(data.CSRFToken)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/view/components/components/modal.templ`, Line: 58, Col: 67}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "\"> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if data.EntityID > 0 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "<input type=\"hidden\" name=\"id\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var7 string
			templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(strconv.FormatInt(data.EntityID, 10))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/view/components/components/modal.templ`, Line: 60, Col: 82}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "\"> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		for _, field := range data.Fields {
			templ_7745c5c3_Err = renderFormField(field).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "<div class=\"modal-footer\"><a href=\"?\" class=\"btn btn-secondary\">Отмена</a> <button type=\"submit\" class=\"btn btn-primary\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if data.EntityID > 0 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "Сохранить")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "Создать")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "</button></div></form></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func InlineEntityForm(data EntityFormData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var8 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var8 == nil {
			templ_7745c5c3_Var8 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "<form method=\"POST\" action=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var9 templ.SafeURL
		templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.JoinURLErrs(data.ActionURL)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/view/components/components/modal.templ`, Line: 83, Col: 44}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var9))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "\" class=\"card card-body\"><input type=\"hidden\" name=\"_method\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var10 string
		templ_7745c5c3_Var10, templ_7745c5c3_Err = templ.JoinStringErrs(data.Method)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/view/components/components/modal.templ`, Line: 84, Col: 57}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var10))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "\"> <input type=\"hidden\" name=\"csrf_token\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var11 string
		templ_7745c5c3_Var11, templ_7745c5c3_Err = templ.JoinStringErrs(data.CSRFToken)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/view/components/components/modal.templ`, Line: 85, Col: 63}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var11))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, "\"> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if data.EntityID > 0 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 18, "<input type=\"hidden\" name=\"id\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var12 string
			templ_7745c5c3_Var12, templ_7745c5c3_Err = templ.JoinStringErrs(strconv.FormatInt(data.EntityID, 10))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/view/components/components/modal.templ`, Line: 87, Col: 78}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var12))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 19, "\"> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		for _, field := range data.Fields {
			templ_7745c5c3_Err = renderFormField(field).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 20, "<div class=\"d-flex justify-content-end\"><button type=\"submit\" class=\"btn btn-primary\">Сохранить</button></div></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func TechnologyFormData(tech models.Technology, allTags []models.Tag, selectedTagIDs map[int64]bool, csrfToken string, isEdit bool) EntityFormData {
	method := "POST"
	if isEdit {
		method = "PUT"
	}

	tagOptions := make([]FormFieldOption, 0, len(allTags))
	for _, tag := range allTags {
		tagOptions = append(tagOptions, FormFieldOption{
			Value:   strconv.FormatInt(tag.ID, 10),
			Label:   tag.Name.Get(i18n.LocaleRU),
			Checked: selectedTagIDs[tag.ID],
			Color:   tag.HexColor,
		})
	}

	return EntityFormData{
		EntityName: "Technology",
		ActionURL:  "/admin/tech",
		Method:     method,
		EntityID:   tech.ID,
		CSRFToken:  csrfToken,
		Fields: []FormField{
			{
				Name:        "title",
				Label:       "Название",
				Type:        "text",
				Value:       tech.Title,
				Placeholder: "Go, Angular",
				Required:    true,
			},
			nullableLocalizedField("description", "Описание", tech.Description, "Описание технологии", true),
			{
				Name:        "logoUrl",
				Label:       "URL логотипа",
				Type:        "url",
				Value:       tech.LogoUrl.String,
				Placeholder: "https://example.com/logo.png",
			},
			{
				Name:    "tagIds",
				Label:   "Теги",
				Type:    "checkbox-group",
				Options: tagOptions,
			},
		},
	}
}

func EducationFormData(edu models.Education, csrfToken string, isEdit bool) EntityFormData {
	method := "POST"
	if isEdit {
		method = "PUT"
	}

	return EntityFormData{
		EntityName: "Education",
		ActionURL:  "/admin/education",
		Method:     method,
		EntityID:   edu.ID,
		CSRFToken:  csrfToken,
		Fields: []FormField{
			nullableLocalizedField("name", "Название", edu.Name, "Название учебного заведения", false),
			{
				Name:        "year",
				Label:       "Год окончания",
				Type:        "number",
				Value:       strconv.Itoa(int(edu.Year)),
				Placeholder: "2020",
				Required:    true,
			},
			localizedTextField("course", "Направление / курс", edu.Course, "Программная инженерия", true, false),
			localizedTextField("organization", "Организация", edu.Organization, "МГТУ им. Баумана", true, false),
		},
	}
}

func WorkHistoryFormData(wh models.WorkHistory, allTechnologies []models.Technology, selectedTechnologyIDs map[int64]bool, csrfToken string, isEdit bool) EntityFormData {
	method := "POST"
	if isEdit {
		method = "PUT"
	}

	periodStart := ""
	if wh.PeriodStart.Valid {
		periodStart = wh.PeriodStart.Time.Format("2006-01-02")
	}
	periodEnd := ""
	if wh.PeriodEnd.Valid {
		periodEnd = wh.PeriodEnd.Time.Format("2006-01-02")
	}

	technologyOptions := make([]FormFieldOption, 0, len(allTechnologies))
	for _, tech := range allTechnologies {
		technologyOptions = append(technologyOptions, FormFieldOption{
			Value:   strconv.FormatInt(tech.ID, 10),
			Label:   tech.Title,
			Checked: selectedTechnologyIDs[tech.ID],
			Color:   "#6c757d",
		})
	}

	return EntityFormData{
		EntityName: "WorkHistory",
		ActionURL:  "/admin/history",
		Method:     method,
		EntityID:   wh.ID,
		CSRFToken:  csrfToken,
		Fields: []FormField{
			localizedTextField("name", "Название компании", wh.Name, "ООО Рога и Копыта", true, false),
			nullableLocalizedField("jobTitle", "Должность", wh.JobTitle, "Senior Backend Developer", false),
			localizedTextField("about", "О компании", wh.About, "Краткое описание компании", true, true),
			{
				Name:        "logoUrl",
				Label:       "URL логотипа",
				Type:        "url",
				Value:       wh.LogoUrl.String,
				Placeholder: "https://example.com/logo.png",
			},
			{
				Name:     "periodStart",
				Label:    "Начало работы",
				Type:     "date",
				Value:    periodStart,
				Required: true,
			},
			{
				Name:  "periodEnd",
				Label: "Конец работы (пусто = по наст. время)",
				Type:  "date",
				Value: periodEnd,
			},
			localizedListField("whatIDid", "Что делал (каждый пункт с новой строки)", wh.WhatIDid, "Разрабатывал микросервисы"),
			localizedListField("projects", "Проекты (каждый с новой строки)", wh.Projects, "Проект А"),
			{
				Name:    "technologyIds",
				Label:   "Технологии",
				Type:    "checkbox-group",
				Options: technologyOptions,
			},
		},
	}
}

func AboutMeFormData(about, note, hobbies i18n.LocalizedText, allTech []models.Technology, selectedTechnologyIDs map[int64]bool, csrfToken string) EntityFormData {
	technologyOptions := make([]FormFieldOption, 0, len(allTech))
	for _, tech := range allTech {
		technologyOptions = append(technologyOptions, FormFieldOption{
			Value:   strconv.FormatInt(tech.ID, 10),
			Label:   tech.Title,
			Checked: selectedTechnologyIDs[tech.ID],
			Color:   "#6c757d",
		})
	}

	return EntityFormData{
		EntityName: "AboutMe",
		ActionURL:  "/admin/about-me",
		Method:     "PUT",
		EntityID:   1,
		CSRFToken:  csrfToken,
		Fields: []FormField{
			localizedTextField("about", "Биография (абзацы через пустую строку)", about, "Первый абзац\n\nВторой абзац", false, true),
			{
				Name:    "technologyIds",
				Label:   "Технологии (бейджи)",
				Type:    "checkbox-group",
				Options: technologyOptions,
			},
			localizedTextField("note", "Заметка", note, "Краткая заметка", false, true),
			localizedTextField("hobbies", "Хобби", hobbies, "Мои хобби: ...", false, true),
		},
	}
}

func HeroFormData(greeting, fullName, title, pitch i18n.LocalizedText, profileID int64, csrfToken string) EntityFormData {
	return EntityFormData{
		EntityName: "Hero",
		ActionURL:  "/admin/hero",
		Method:     "PUT",
		EntityID:   profileID,
		CSRFToken:  csrfToken,
		Fields: []FormField{
			localizedTextField("greeting", "Приветствие", greeting, "Здравствуйте!", true, false),
			localizedTextField("fullName", "Имя", fullName, "Балашов Максим", true, false),
			localizedTextField("title", "Должность", title, "Full-Stack разработчик", true, false),
			localizedTextField("pitch", "Краткое описание", pitch, "Эта страница рассказывает...", false, true),
		},
	}
}

func TagFormData(tag models.Tag, csrfToken string, isEdit bool) EntityFormData {
	method := "POST"
	if isEdit {
		method = "PUT"
	}

	return EntityFormData{
		EntityName: "Tag",
		ActionURL:  "/admin/tag",
		Method:     method,
		EntityID:   tag.ID,
		CSRFToken:  csrfToken,
		Fields: []FormField{
			localizedTextField("name", "Название", tag.Name, "Frontend", true, false),
			{
				Name:        "hexColor",
				Label:       "Цвет (HEX)",
				Type:        "color",
				Value:       tag.HexColor,
				Placeholder: "#FF0077",
				Required:    true,
			},
		},
	}
}

var _ = templruntime.GeneratedTemplate
